
const categories = [
    {
        id: 1,
        name: 'Phones',
        thumbnail: 'store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-12-og-202104?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1617339367000',
    },
    {
        id: 2,
        name: 'Computers',
        thumbnail: 'prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/33/3301045/APPLE-MacBook-Pro-16-Srebrny.jpg',
    },
    {
        id: 3,
        name: 'Smart Watch',
        thumbnail: 'www.apple.com/newsroom/images/product/watch/standard/Apple-watch-watchos7_three-watchfaces_06222020.jpg.landing-big_2x.jpg',
    },
    {
        id: 4,
        name: 'Tablets',
        thumbnail: 'media.revistagq.com/photos/614b0cd12efa7ebc613dcc10/master/pass/Apple_iPad-mini_colors_09142021.jpg'
    }

]