const brands = [
    {
        id: 1,
        name: 'Alcatel',
        image: 'e7.pngegg.com/pngimages/80/345/png-clipart-alcatel-mobile-telephone-telecommunication-alcatel-one-touch-iphone-iphone-angle-electronics.png'
    },
    {
        id: 2,
        name: 'Apple',
        image: 'w7.pngwing.com/pngs/654/859/png-transparent-apple-logo-cupertino-cartoon-crowd-company-computer-logo.png'
    },
    {
        id: 3,
        name: 'Motorola',
        image: 'e7.pngegg.com/pngimages/932/415/png-clipart-motorola-xoom-logo-motorola-solutions-iphone-electronics-text.png'
    },
    {
        id: 4,
        name: 'Samsung',
        image: 'e7.pngegg.com/pngimages/717/794/png-clipart-logo-apple-inc-v-samsung-electronics-co-business-samsung-text-logo.png'
    }
]